# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSSeminarChallenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.3'
  # Pods for iOSSeminarChallenge

  target 'iOSSeminarChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSSeminarChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
